CookieAuthentication/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CookieAuthentication.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CookieAuthentication/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace CookieAuthentication.Pages;

[BindProperties]
public class IndexModel : PageModel
{
    public LoginInput UserLogin { get; set; }
    

    public void OnGet()
    {

    }
    public async Task<IActionResult> OnPostSignIn() { 
        if (ModelState.IsValid)
        {
            if(UserLogin.Username == "intern" && UserLogin.Password == "summer 2023 july")
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, UserLogin.Username),
                    new Claim(ClaimTypes.Role, "Intern")
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    IssuedUtc = DateTimeOffset.UtcNow,
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(30)
                };
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
                return RedirectToPage();
            }
        }
        ModelState.AddModelError("", "Invalid Login Attempt");
        return Page();
    }


    public async Task<IActionResult> OnPostSignOut()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToPage();
    }
}

public class LoginInput
{
    [Required]
    public string Username { get; set; }
    [Required]
    public string Password { get; set; }
}

CookieAuthentication/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CookieAuthentication.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CookieAuthentication/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@{
    if (!User.Identity.IsAuthenticated)
    {
        <div class="container d-flex justify-content-center align-items-center mt-5">
            <div class="row">
                <div class="col">
                    <div class="card shadow">
                        <h1 class="card-img-top d-flex justify-content-center pt-3">Sign In</h1>
                        <div class="card-body">
                            <form method="post" asp-page-handler="SignIn">                    
                                <div class="mb-3">
                                    <label class="form-label" for="Username">Username</label>
                                    <input asp-for="UserLogin.Username" class="form-control" type="text" name="UserLogin.Username">
                                    <span asp-validation-for="UserLogin.Username" class="text-danger"></span>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label" for="Password">Password</label>
                                    <input asp-for="UserLogin.Password" class="form-control" type="password" name="UserLogin.Password">
                                    <span asp-validation-for="UserLogin.Password" class="text-danger"></span>
                                </div>
                                <div asp-validation-summary="ModelOnly" class="text-danger">
                                </div>
                                <button class="btn btn-success d-flex justify-content-center">Login</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="container d-flex justify-content-center align-items-center mt-5">
            <div class="row">
                <div class="col">
                    <div class="card shadow">
                        <h1 class="card-img-top d-flex justify-content-center p-3">Welcome @User.Identity.Name</h1>
                        <div class="card-body">
                            <form method="post" asp-page-handler="SignOut">
                                <button class="btn btn-danger d-flex justify-content-center">Logout</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CookieAuthentication/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CookieAuthentication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CookieAuthentication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CookieAuthentication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CookieAuthentication - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>